### ISSUE TITLE
Background images for tracing

### ISSUE THREAD

**Issue by NonWonderDog** [Inglonias/VGraph#44]
The ability to import a background image to trace over would be a huge boon for e.g. translating orthographic drawings into FTD replicas.

Some auxiliary features for usability:

1) The ability to set and change the image scale (in source image pixels per grid square).
2) The ability to set and change the X/Y offset for the image.
3) An opacity slider.
4) The ability to save the background image name and settings to the project file.

**Comment by Inglonias** [comment]
Nothing about this feature request is all that difficult. I wanted to be able to adjust the background and grid colors anyway, which would also be helpful.

The only thing I might need is an example of the sort of image you're talking about for reference. Does this image search for [orthographic drawing boat](https://www.google.com/search?q=orthographic+drawing+boat&tbm=isch) give back the sort of stuff you work with?

**Notes for reference**
[How to access and transform the pixels of a SKBitmap object.](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/pixel-bits#the-techniques) Note that some methods of accessing all the pixels are much faster than others.

**Comment by NonWonderDog** [comment]
Exactly those kind of drawings.

The point on scale is essentially that it's not always possible to do an exactly 100% scale replica, and that it could be useful to sweep through and find the scale where things best align to the grid, whether that be at 97% or 120% or whatever.  Similarly with x/y offset, since any origin point is going to be a compromise.  But this is a set once and never touch it again kind of thing, so it could always be done in an external tool.

**Comment by Inglonias** [comment]
The initial implementation has been merged into the main branch.

**Comment by Inglonias** [comment]
The implementation I have has been released with VGraph 1.9. Feel free to create a new issue if the background image feature needs some adjusting.
